# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  push:
    branches-ignore:
      - gh-pages
    tags:
      - "*"
  schedule:
    - cron: 59 14 * * *
  pull_request: null
name: update docs

jobs:
  docs:
    if: github.event_name != 'schedule' || github.repository == 'planetarium/libplanet'
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        if: github.event_name != 'pull_request'
      - uses: actions/checkout@main
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.pull_request.head.sha }}
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: dotnet build -p:SkipSonar=true
      - run: mkdir -p Docs/obj/
      - run: Docs/build.ps1
        shell: pwsh
      - uses: actions/upload-artifact@main
        with:
          name: docs
          path: Docs/_site/
      - run: Docs/publish.sh
        env:
          GHPAGES_SSH_KEY: ${{ secrets.GHPAGES_SSH_KEY }}
        if: github.event_name != 'pull_request'
      - id: docs-url
        run: 'echo ::set-output name=url::"$(cat Docs/obj/url.txt)"'
        if: github.event_name != 'pull_request'
      - uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: docs
          description: Libplanet docs generated by DocFX
          state: 'success'
          target_url: ${{ steps.docs-url.outputs.url }}
        if: github.event_name != 'pull_request'
